### ISSUE TITLE
Compras - General

### ISSUE THREAD

**Issue by sperzero** [suavid/compras#1]
Retirar texto de plantilla "GUI powered by MetroUI, found on http://metroui.org.ua/"

Ruta: /compras/compras/productos

<a href='http://www.subirimagenes.com/privadas-sinttulo-2371632.html'><img src='http://s2.subirimagenes.com/privadas/previo/thump_2371632sin-ttulo.png' alt='subir imagenes' border='0'></a>

**Comment by sperzero** [comment]
PD. Problemas para ingresar a la pestaña "Productos" posiblemente es cuestión de permisos.

**Comment by suavid** [comment]
Ok, retirare el texto hoy en la noche. Y el problema de permisos asi debe de ser, te da acceso a los productos SOLO si no tenes instalado el modulo de inventarios. Pero como el modulo de inventarios esta instalado se va a gestionar desde ahi. Deje eso asi por si en algun momento se necesita deshabilitar el modulo por alguna razon igual se puedan ingresar productos desde otro modulo, solo va a funcionar si el de inventarios no esta en funcionamiento :)

**Comment by suavid** [comment]
mensaje removido :) ya subi los cambios
