### ISSUE TITLE
Recepcion de Productos

### ISSUE THREAD

**Issue by sperzero** [suavid/compras#10]
Ruta: /compras/compras/recepcion?id=40

agregar validación para no permitir que los productos no caigan en stock negativo al realizar una operación de  rollback

![image](https://cloud.githubusercontent.com/assets/8403472/16749225/e6d20bea-4785-11e6-9034-421de662b716.png)

**Comment by suavid** [comment]
voy a cerrar este issue, esta validación no es necesaria, los cambios no se aplican al stock hasta que confirmas el documento completo, el hacer rollback no afecta stock, solo afecta el documento de la oc :)
