### ISSUE TITLE
Recepción de productos

### ISSUE THREAD

**Issue by sperzero** [suavid/compras#11]
Ruta: /compras/compras/recepcion?id=40

una ves se a realizado la pila de actividades en la recepción de un producto, y se desea retirar, un producto de la pila elimina todo el historial del mismo producto.

![image](https://cloud.githubusercontent.com/assets/8403472/16749309/791cd84a-4786-11e6-81cf-17a3e2090dec.png)

![image](https://cloud.githubusercontent.com/assets/8403472/16749380/f623e108-4786-11e6-85b5-f4987bee78f1.png)

**Comment by suavid** [comment]
Resuelto
