### ISSUE TITLE
Ficha del Proveedor

### ISSUE THREAD

**Issue by sperzero** [suavid/compras#12]
Ruta: /compras/compras/proveedores

Al parecer con el comit que falta por hacer se resuelven la mayoría, si no es que todos los problemas de este modulo, por lo tanto, dispuse de hacer una ultima comparación entre el sistema actual (la base de la que partimos) hacia lo que tenemos.

Falta agregar estos campos a la ficha de proveedor

![image](https://cloud.githubusercontent.com/assets/8403472/16887610/5b5f8d24-4a98-11e6-9226-844677e4ce47.png)

**Comment by suavid** [comment]
ALTER TABLE `nymsal`.`proveedor` 
CHANGE COLUMN `margen_usual` `margen_usual` DECIMAL(10,2) NULL DEFAULT 0.0 ,
CHANGE COLUMN `descuento_aplicable` `descuento_aplicable` DECIMAL(10,2) NULL DEFAULT 0.0 ;

Solucionado, correr este script en la base.
