### ISSUE TITLE
Solicitud de Orden de Compra

### ISSUE THREAD

**Issue by sperzero** [suavid/compras#13]
Ruta: /compras/compras/solicitud_orden

Falta agregar el campo "fecha de entrega" el cual es calculado a partir de los días de entrega que maneja el proveedor.

Falta agregar los datos de la persona que autorizo la OC (usuario de sistema). 

![image](https://cloud.githubusercontent.com/assets/8403472/16888763/539e23aa-4a9f-11e6-9ff1-cdc07d73523a.png)

**Comment by suavid** [comment]
Los datos del usuario si se agregan solo que no se los muestra al usuario, pero si están

**Comment by suavid** [comment]
En este necesito que me aclares, porque en un commit anterior pusimos la fecha en la que va a llegar el producto con un datepicker, pero acá me decís que lo calcule con los días de entrega del proveedor.  cómo lo dejo?

**Comment by sperzero** [comment]
Aclarando un poco el tema de la fecha de entrega, se utilizaran los 2 criterios, pues de manera automática el sistema asignara una fecha tentativa de entrega y posteriormente (antes de la confirmación ) podrá ser cambiado por medio del datepicker.

**Comment by suavid** [comment]
Resuelto
