### ISSUE TITLE
Consultar Orden De Compra

### ISSUE THREAD

**Issue by sperzero** [suavid/compras#14]
Ruta:  /compras/compras/consultarOc

Agregar opción para exportar a Exel

![image](https://cloud.githubusercontent.com/assets/8403472/16888955/5aa6914a-4aa0-11e6-8488-043154f345b2.png)

![image](https://cloud.githubusercontent.com/assets/8403472/16889173/bfc5ea98-4aa1-11e6-8ccc-290d6f557453.png)

**Comment by suavid** [comment]
Resuelto
