### ISSUE TITLE
Compras - General

### ISSUE THREAD

**Issue by sperzero** [suavid/compras#16]
Al revisar un poco la forma en la que se navega por la interfaz del sistema es necesario re-ordenar algunos menús  y re-nombrarlos de esta forma:

Nombre actual                             ||     Nuevo Nombre
____________________________________________________________________

* Pedidos                                      -     (Orden de Compras)
       - Consultar OC                      -
       - Crear pedido                       -     (Crear OC)
       - Liberar pedido                     -     (Aprobar OC)
       - Recepción de mercadería    -    (Recepción de OC)

*Proveedores

*Productos

*Productos en transito

![image](https://cloud.githubusercontent.com/assets/8403472/16889576/b02fe130-4aa4-11e6-8f8c-20cf412b7f28.png)

**Comment by suavid** [comment]
Resuelto
