### ISSUE TITLE
Impresión de OC

### ISSUE THREAD

**Issue by sperzero** [suavid/compras#17]
Ruta: /compras/compras/preview?solicitud=34

Cambiar el logo antiguo, por el nuevo que aparece en el home

![image](https://cloud.githubusercontent.com/assets/8403472/16889596/d51530cc-4aa4-11e6-8f85-f0169cbbf978.png)

![image](https://cloud.githubusercontent.com/assets/8403472/16889603/ec6e1220-4aa4-11e6-8b5b-15643938f840.png)

**Comment by suavid** [comment]
Resuelto
