### ISSUE TITLE
Registrar proveedor

### ISSUE THREAD

**Issue by sperzero** [suavid/compras#19]
Ruta: /compras/compras/proveedores

-agregar validación al campo "días crédito" ya que este permite poner letras, ademas colocar valor inicial por defecto de este campo como cero, "0".

-colocar valor inicial de campo "días de entrega" como cero, "0"

-colocar como valor inicial al campo "margen usual" inicial por defecto como el "35%"

-colocar como valor inicial al campo "descuento aplicable" cero, "0%"

![image](https://cloud.githubusercontent.com/assets/8403472/17786665/1f9c5a72-6543-11e6-8219-b15497b8e607.png)

**Comment by suavid** [comment]
Resuelto
