### ISSUE TITLE
Compras - Proveedores

### ISSUE THREAD

**Issue by sperzero** [suavid/compras#2]
Error al guardar un nuevo proveedor, posible problema en BD.

![image](https://cloud.githubusercontent.com/assets/8403472/15830096/e5508936-2bd3-11e6-9d02-9d8d32b51802.png)

**Comment by suavid** [comment]
Creo que el problema no es la BD sino el archivo de configuracion, creo que te puse uno viejo. Proba irte al archivo de configuracion y mira que base de datos tiene, si tiene db_inventario ponele nymsaL...

Si el problema no esta en el archivo de configuracion posiblemente haya dejado la base de datos puesta como cadena en codigo, si este es el caso entonces lo cambiare hoy en la noche, pero ningun modulo deberia estarse tratando de conectar a otra base que no sea NymsaL :)

**Comment by sperzero** [comment]
eh revisado los archivos de configuracion, es que esta en la ruta \BM_CONFIG\inventario ya tiene la base nymsaL, al mismo tiempo eh revisado el resto de archivos de configuración y estos estan igual...

**Comment by suavid** [comment]
Dame chance que esta semana mi padre ha tenido vacaciones y me pidio estar esta semana en casa de el y no tengo acceso a mi pc :( en tan pronto lo tengo reviso el problema

**Comment by suavid** [comment]
Ya arregle el problema, como te comenté, resultó que la conexión a la base estaba escrita directamente en el código, ya subí los cambios a github, los podés descargar
