### ISSUE TITLE
Visualzar Proveedor

### ISSUE THREAD

**Issue by sperzero** [suavid/compras#20]
Ruta: /compras/compras/proveedores

Problemas al revisar palabras con tildes.

![image](https://cloud.githubusercontent.com/assets/8403472/17788254/eed4170c-6549-11e6-9bba-b6d03861a547.png)

**Comment by suavid** [comment]
Puya, después de darme riata como loco, logré arreglar eso vv, el problema no era al visualizar, el problema era al guardar los datos :(
