### ISSUE TITLE
Recepción de OC

### ISSUE THREAD

**Issue by sperzero** [suavid/compras#21]
Ruta: /compras/compras/recepcion?id=51

Problemas con la forma en la que se maneja el stock temporal de los productos que se reciben en una OC, me encanta la forma en que se gestiona, solo es de afinarlo un poco.

hoy me tope con este error.

OC en su modo de vista
![image](https://cloud.githubusercontent.com/assets/8403472/17790778/54c32e1c-6555-11e6-9b28-f142a43c3efb.png)

OC en recepción de productos (se a dado de baja a ambos productos)
![image](https://cloud.githubusercontent.com/assets/8403472/17790955/11c3c5da-6556-11e6-973a-c1959b3b369a.png)

OC después de darle revertir a los cambios.
![image](https://cloud.githubusercontent.com/assets/8403472/17790982/2f2005c6-6556-11e6-94e5-979dd6245faa.png)

Para  revisar si era un error temporal salí del modulo y volví a entrar a recepción de OC
![image](https://cloud.githubusercontent.com/assets/8403472/17791023/62e2e2c0-6556-11e6-844d-55ae679595de.png)

Intentando ingresar unidades positivas para cancelarlas con las negativas
![image](https://cloud.githubusercontent.com/assets/8403472/17791082/b1835cd4-6556-11e6-890b-4634f8840c61.png)

**Comment by sperzero** [comment]
creería que la mayoría de este problema se solventaría no dejando que el stock temporal baje de cero, aunque queda por analizar porque sea aumentan los articulos a recibir

**Comment by suavid** [comment]
Resuelto, me costó encontrarle pero era un update sin where :/
