### ISSUE TITLE
Proveedores

### ISSUE THREAD

**Issue by sperzero** [suavid/compras#3]
Dirección: /compras/compras/proveedores

Es posible eliminar proveedores que cuentan con algún tipo de relación, solo deberían de poder ser eliminados aquellos que no tienen relación con otras tablas

![image](https://cloud.githubusercontent.com/assets/8403472/16276114/470661b2-386a-11e6-917d-4500b1ee1252.png)

**Comment by suavid** [comment]
Problema solucionado
