### ISSUE TITLE
Ordenen de compra

### ISSUE THREAD

**Issue by sperzero** [suavid/compras#4]
Ruta: /compras/compras/solicitud_orden

Una ves la O.C. ah sido confirmada aparecen los botones eliminar en el formulario, estos botones devén de ser removidos pues en este apartado la OC solo es de lectura, ya que hay otro lugar donde se procesan las OC.

PD. Al presionar eliminar en los botones no realizan ninguna acción

![image](https://cloud.githubusercontent.com/assets/8403472/16277190/15d89600-386f-11e6-98f1-dca59d636122.png)

**Comment by suavid** [comment]
problema resuelto
