### ISSUE TITLE
Orden de compra

### ISSUE THREAD

**Issue by sperzero** [suavid/compras#5]
Ruta: /compras/compras/compras

Incluir opcion para cancelar orden de compra aunque esta ya este aprobada para ser recibida, pues es frecuente que el proveedor agote sus existencias antes de surtir el producto a la empresa, se le termine la materia prima.... u otras causas por las cuales el proveedor no pueda surtir a la empresa con la OC.

![image](https://cloud.githubusercontent.com/assets/8403472/16277365/da16818a-386f-11e6-8c23-c0e00984a8be.png)

**Comment by suavid** [comment]
Para este caso existe la opción de dar de baja al producto. No había considerado que fuera bueno cancelar una OC ya aprobada, en este caso lo mejor es ir a procesarla y dar de baja todo el producto y queda ya saldada.
