### ISSUE TITLE
Orden de compra

### ISSUE THREAD

**Issue by sperzero** [suavid/compras#6]
Ruta: /compras/compras/solicitud_orden

Falta agregar la fecha en la se prevee que el producto llegara a la empresa, pues este es rellenado con 0-000-000, utilizar calendario para seleccionar la fecha exacta.

![image](https://cloud.githubusercontent.com/assets/8403472/16277450/3cf6817e-3870-11e6-8dd6-31371d4ef044.png)

**Comment by suavid** [comment]
Resuelto
