### ISSUE TITLE
proveedores 

### ISSUE THREAD

**Issue by sperzero** [suavid/compras#7]
Ruta: /compras/compras/proveedores

Error al eliminar proveedores, este proveedor fue agregado y posteriormente eliminado, sin tener ninguna dependencia, inicialmente mostró ese mensaje de error al intentar ser eliminado, pero al cambiar la paginacion del formulario este elimino el registro.

![image](https://cloud.githubusercontent.com/assets/8403472/16748265/58549810-4780-11e6-94ad-969bafc86f6c.png)

![image](https://cloud.githubusercontent.com/assets/8403472/16748339/ba601142-4780-11e6-8fb1-3a71fb176617.png)

**Comment by suavid** [comment]
Este problema ya fue solucionado, aún no voy a subir el commit a git, haré commit cuando haya solucionado varios issues, pero este problema tiene dos partes, el de la aplicación que se soluciona con el commit y un bug de la base que se arregla con el script atachado. De ser posible correrlo por partes según indica el script
[fix.txt](https://github.com/suavid/compras/files/358407/fix.txt)

Cerrare el issue
